name: sat solver
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone codes
      uses: actions/checkout@v2
    - name: Build
      run: make docker-build
    - name: Test
      run: make docker-run-test
